# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skillcheck.ui'
#
# Created: Mon Mar 17 08:44:16 2014
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(370, 570)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(370, 570))
        MainWindow.setMaximumSize(QtCore.QSize(370, 570))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sc_icon_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.actionsBox = QtGui.QGroupBox(self.centralwidget)
        self.actionsBox.setGeometry(QtCore.QRect(10, 0, 351, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Eras Demi ITC"))
        font.setItalic(False)
        self.actionsBox.setFont(font)
        self.actionsBox.setObjectName(_fromUtf8("actionsBox"))
        self.label_4 = QtGui.QLabel(self.actionsBox)
        self.label_4.setGeometry(QtCore.QRect(250, 140, 16, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.clearButton = QtGui.QPushButton(self.actionsBox)
        self.clearButton.setGeometry(QtCore.QRect(10, 170, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.effectlabel = QtGui.QLabel(self.actionsBox)
        self.effectlabel.setGeometry(QtCore.QRect(90, 170, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.effectlabel.setFont(font)
        self.effectlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.effectlabel.setObjectName(_fromUtf8("effectlabel"))
        self.rollButton = QtGui.QPushButton(self.actionsBox)
        self.rollButton.setGeometry(QtCore.QRect(10, 80, 61, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollButton.setFont(font)
        self.rollButton.setFlat(False)
        self.rollButton.setObjectName(_fromUtf8("rollButton"))
        self.label_7 = QtGui.QLabel(self.actionsBox)
        self.label_7.setGeometry(QtCore.QRect(200, 140, 21, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.effect_result = QtGui.QLabel(self.actionsBox)
        self.effect_result.setGeometry(QtCore.QRect(130, 170, 211, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect_result.sizePolicy().hasHeightForWidth())
        self.effect_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.effect_result.setFont(font)
        self.effect_result.setFrameShape(QtGui.QFrame.Box)
        self.effect_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.effect_result.setText(_fromUtf8(""))
        self.effect_result.setAlignment(QtCore.Qt.AlignCenter)
        self.effect_result.setObjectName(_fromUtf8("effect_result"))
        self.label = QtGui.QLabel(self.actionsBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.diffdial = QtGui.QDial(self.actionsBox)
        self.diffdial.setGeometry(QtCore.QRect(200, 80, 71, 71))
        self.diffdial.setMinimum(-6)
        self.diffdial.setMaximum(6)
        self.diffdial.setSingleStep(2)
        self.diffdial.setPageStep(2)
        self.diffdial.setSliderPosition(0)
        self.diffdial.setTracking(True)
        self.diffdial.setWrapping(False)
        self.diffdial.setNotchTarget(3.7)
        self.diffdial.setNotchesVisible(True)
        self.diffdial.setObjectName(_fromUtf8("diffdial"))
        self.plus_sign_2 = QtGui.QLabel(self.actionsBox)
        self.plus_sign_2.setGeometry(QtCore.QRect(150, 50, 16, 16))
        self.plus_sign_2.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_2.setObjectName(_fromUtf8("plus_sign_2"))
        self.plus_sign = QtGui.QLabel(self.actionsBox)
        self.plus_sign.setGeometry(QtCore.QRect(70, 50, 16, 16))
        self.plus_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign.setObjectName(_fromUtf8("plus_sign"))
        self.plus_sign_3 = QtGui.QLabel(self.actionsBox)
        self.plus_sign_3.setGeometry(QtCore.QRect(230, 50, 16, 16))
        self.plus_sign_3.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_3.setObjectName(_fromUtf8("plus_sign_3"))
        self.minus_sign = QtGui.QLabel(self.actionsBox)
        self.minus_sign.setGeometry(QtCore.QRect(290, 50, 16, 16))
        self.minus_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.minus_sign.setObjectName(_fromUtf8("minus_sign"))
        self.resultlabel = QtGui.QLabel(self.actionsBox)
        self.resultlabel.setGeometry(QtCore.QRect(280, 90, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultlabel.setFont(font)
        self.resultlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultlabel.setObjectName(_fromUtf8("resultlabel"))
        self.die_result = QtGui.QLabel(self.actionsBox)
        self.die_result.setGeometry(QtCore.QRect(281, 109, 61, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.die_result.sizePolicy().hasHeightForWidth())
        self.die_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Eras Demi ITC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.die_result.setFont(font)
        self.die_result.setFrameShape(QtGui.QFrame.Box)
        self.die_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.die_result.setText(_fromUtf8(""))
        self.die_result.setAlignment(QtCore.Qt.AlignCenter)
        self.die_result.setObjectName(_fromUtf8("die_result"))
        self.totalDM = QtGui.QLabel(self.actionsBox)
        self.totalDM.setGeometry(QtCore.QRect(311, 41, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalDM.sizePolicy().hasHeightForWidth())
        self.totalDM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalDM.setFont(font)
        self.totalDM.setFrameShape(QtGui.QFrame.Box)
        self.totalDM.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalDM.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDM.setObjectName(_fromUtf8("totalDM"))
        self.totalDiff = QtGui.QLabel(self.actionsBox)
        self.totalDiff.setGeometry(QtCore.QRect(251, 41, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalDiff.sizePolicy().hasHeightForWidth())
        self.totalDiff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalDiff.setFont(font)
        self.totalDiff.setFrameShape(QtGui.QFrame.Box)
        self.totalDiff.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalDiff.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDiff.setObjectName(_fromUtf8("totalDiff"))
        self.inputDM = QtGui.QSpinBox(self.actionsBox)
        self.inputDM.setGeometry(QtCore.QRect(171, 41, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputDM.setFont(font)
        self.inputDM.setFrame(True)
        self.inputDM.setAlignment(QtCore.Qt.AlignCenter)
        self.inputDM.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputDM.setMinimum(-99)
        self.inputDM.setMaximum(99)
        self.inputDM.setObjectName(_fromUtf8("inputDM"))
        self.inputcharmod = QtGui.QSpinBox(self.actionsBox)
        self.inputcharmod.setGeometry(QtCore.QRect(91, 41, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputcharmod.setFont(font)
        self.inputcharmod.setFrame(True)
        self.inputcharmod.setAlignment(QtCore.Qt.AlignCenter)
        self.inputcharmod.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.inputcharmod.setMinimum(-3)
        self.inputcharmod.setMaximum(5)
        self.inputcharmod.setObjectName(_fromUtf8("inputcharmod"))
        self.inputskilllevel = QtGui.QSpinBox(self.actionsBox)
        self.inputskilllevel.setGeometry(QtCore.QRect(11, 41, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputskilllevel.setFont(font)
        self.inputskilllevel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputskilllevel.setMinimum(-3)
        self.inputskilllevel.setMaximum(7)
        self.inputskilllevel.setSingleStep(1)
        self.inputskilllevel.setObjectName(_fromUtf8("inputskilllevel"))
        self.die1Label = QtGui.QLabel(self.actionsBox)
        self.die1Label.setGeometry(QtCore.QRect(80, 100, 48, 48))
        self.die1Label.setText(_fromUtf8(""))
        self.die1Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die1_0.png")))
        self.die1Label.setObjectName(_fromUtf8("die1Label"))
        self.die2Label = QtGui.QLabel(self.actionsBox)
        self.die2Label.setGeometry(QtCore.QRect(140, 100, 48, 48))
        self.die2Label.setText(_fromUtf8(""))
        self.die2Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/die2_0.png")))
        self.die2Label.setObjectName(_fromUtf8("die2Label"))
        self.outcomesBox = QtGui.QGroupBox(self.centralwidget)
        self.outcomesBox.setGeometry(QtCore.QRect(10, 210, 351, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Eras Demi ITC"))
        self.outcomesBox.setFont(font)
        self.outcomesBox.setObjectName(_fromUtf8("outcomesBox"))
        self.mpl = MplWidget(self.outcomesBox)
        self.mpl.setGeometry(QtCore.QRect(10, 20, 331, 261))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.brandlabel = QtGui.QLabel(self.centralwidget)
        self.brandlabel.setGeometry(QtCore.QRect(200, 500, 171, 31))
        self.brandlabel.setText(_fromUtf8(""))
        self.brandlabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/shonner_brand.png")))
        self.brandlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.brandlabel.setObjectName(_fromUtf8("brandlabel"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAudio_Test = QtGui.QMenu(self.menuSettings)
        self.menuAudio_Test.setStatusTip(_fromUtf8(""))
        self.menuAudio_Test.setObjectName(_fromUtf8("menuAudio_Test"))
        self.menuWeb = QtGui.QMenu(self.menubar)
        self.menuWeb.setObjectName(_fromUtf8("menuWeb"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRoll = QtGui.QAction(MainWindow)
        self.actionRoll.setObjectName(_fromUtf8("actionRoll"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPlaySample = QtGui.QAction(MainWindow)
        self.actionPlaySample.setEnabled(False)
        self.actionPlaySample.setObjectName(_fromUtf8("actionPlaySample"))
        self.actionUnMute = QtGui.QAction(MainWindow)
        self.actionUnMute.setObjectName(_fromUtf8("actionUnMute"))
        self.actionMute = QtGui.QAction(MainWindow)
        self.actionMute.setObjectName(_fromUtf8("actionMute"))
        self.actionVisit_Shonner = QtGui.QAction(MainWindow)
        self.actionVisit_Shonner.setObjectName(_fromUtf8("actionVisit_Shonner"))
        self.actionTech_Support = QtGui.QAction(MainWindow)
        self.actionTech_Support.setObjectName(_fromUtf8("actionTech_Support"))
        self.actionOverview = QtGui.QAction(MainWindow)
        self.actionOverview.setObjectName(_fromUtf8("actionOverview"))
        self.actionAbout_Skill_Check = QtGui.QAction(MainWindow)
        self.actionAbout_Skill_Check.setObjectName(_fromUtf8("actionAbout_Skill_Check"))
        self.menuAction.addAction(self.actionRoll)
        self.menuAction.addAction(self.actionClear)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionQuit)
        self.menuAudio_Test.addAction(self.actionPlaySample)
        self.menuAudio_Test.addAction(self.actionUnMute)
        self.menuAudio_Test.addAction(self.actionMute)
        self.menuSettings.addAction(self.menuAudio_Test.menuAction())
        self.menuWeb.addAction(self.actionVisit_Shonner)
        self.menuWeb.addAction(self.actionTech_Support)
        self.menuHelp.addAction(self.actionOverview)
        self.menuHelp.addAction(self.actionAbout_Skill_Check)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWeb.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputskilllevel, self.inputcharmod)
        MainWindow.setTabOrder(self.inputcharmod, self.inputDM)
        MainWindow.setTabOrder(self.inputDM, self.rollButton)
        MainWindow.setTabOrder(self.rollButton, self.diffdial)
        MainWindow.setTabOrder(self.diffdial, self.clearButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Skill Check 0.7.6 (Beta)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsBox.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "+6", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear all fields", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.effectlabel.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.rollButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Roll two 6-sided dice", None, QtGui.QApplication.UnicodeUTF8))
        self.rollButton.setText(QtGui.QApplication.translate("MainWindow", "Roll\n"
"2D6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "-6", None, QtGui.QApplication.UnicodeUTF8))
        self.effect_result.setToolTip(QtGui.QApplication.translate("MainWindow", "The effect of the roll", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Skill Level      Char Mod     Added DM     Difficulty      DMs", None, QtGui.QApplication.UnicodeUTF8))
        self.diffdial.setToolTip(QtGui.QApplication.translate("MainWindow", "Adust level of difficulty", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_2.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_sign_3.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.minus_sign.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.resultlabel.setText(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.die_result.setToolTip(QtGui.QApplication.translate("MainWindow", "Total roll result", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Dice modifier total", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDM.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDiff.setToolTip(QtGui.QApplication.translate("MainWindow", "Difficulty level", None, QtGui.QApplication.UnicodeUTF8))
        self.totalDiff.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inputDM.setToolTip(QtGui.QApplication.translate("MainWindow", "Added dice modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.inputcharmod.setToolTip(QtGui.QApplication.translate("MainWindow", "Characteristic modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.inputskilllevel.setToolTip(QtGui.QApplication.translate("MainWindow", "Skill level", None, QtGui.QApplication.UnicodeUTF8))
        self.die1Label.setStatusTip(QtGui.QApplication.translate("MainWindow", "First die", None, QtGui.QApplication.UnicodeUTF8))
        self.die2Label.setStatusTip(QtGui.QApplication.translate("MainWindow", "Second die", None, QtGui.QApplication.UnicodeUTF8))
        self.outcomesBox.setTitle(QtGui.QApplication.translate("MainWindow", "Outcomes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAudio_Test.setTitle(QtGui.QApplication.translate("MainWindow", "Audio Test", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWeb.setTitle(QtGui.QApplication.translate("MainWindow", "Web", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll.setText(QtGui.QApplication.translate("MainWindow", "Roll 2D6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll.setStatusTip(QtGui.QApplication.translate("MainWindow", "Roll two 6-sided dice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRoll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear all fields", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaySample.setText(QtGui.QApplication.translate("MainWindow", "Play Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaySample.setStatusTip(QtGui.QApplication.translate("MainWindow", "Perform an audio test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaySample.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnMute.setText(QtGui.QApplication.translate("MainWindow", "Un-Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnMute.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enable audio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnMute.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMute.setText(QtGui.QApplication.translate("MainWindow", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMute.setStatusTip(QtGui.QApplication.translate("MainWindow", "Disable audio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMute.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisit_Shonner.setText(QtGui.QApplication.translate("MainWindow", "Visit Shonner", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisit_Shonner.setStatusTip(QtGui.QApplication.translate("MainWindow", "Visit Shonner on the web", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTech_Support.setText(QtGui.QApplication.translate("MainWindow", "Tech Support", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTech_Support.setIconText(QtGui.QApplication.translate("MainWindow", "Tech Support", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTech_Support.setStatusTip(QtGui.QApplication.translate("MainWindow", "Contact tech support", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverview.setText(QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverview.setStatusTip(QtGui.QApplication.translate("MainWindow", "Give an overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverview.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Skill_Check.setText(QtGui.QApplication.translate("MainWindow", "About Skill Check", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Skill_Check.setStatusTip(QtGui.QApplication.translate("MainWindow", "About Skill Check", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
import skillcheck_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

